# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('vid', 'vid'), ('img', 'image')], max_length=3)),
                ('caption', models.TextField()),
                ('recorded_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
