# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='media_type',
            field=models.CharField(choices=[('vid', 'vid'), ('img', 'img')], default='img', max_length=3),
        ),
    ]
